# Generated by Django 5.0.6 on 2024-07-26 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('request_data', models.DateTimeField(auto_now_add=True)),
                ('response_data', models.TextField()),
                ('user_pr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_request', to='weather_app.profile')),
            ],
        ),
    ]
